### ISSUE TITLE
Absolutely Great except constantly not responding

### ISSUE THREAD

**Issue by TheNameOfAnAmatuer** [daniyalw/tkinter-terminal#1]
So Im integrating The terminal into an IDE Im working on but whenever I try to run powershell or run python files its not responding

**Comment by daniyalw** [comment]
Yeah, it's because it does not create a new thread when executing user input. So when the user decides to run something with an infinite loop (like an app), then the terminal hangs. I should probably fix this soon.

**Comment by TheNameOfAnAmatuer** [comment]
I know this is a late reply But
Thanks for responding
i have stopped that project anyway (:
