### ISSUE TITLE
Error: cant use cd command

### ISSUE THREAD

**Issue by arnav56745** [daniyalw/tkinter-terminal#2]
I want to use 'cd' command but it says 'Error: cannot use "cd" command in terminal.'

**Comment by daniyalw** [comment]
Yes, because when I wrote this code I could not figure out how to implement "cd". 

I will look into it and possibly will add "cd" functionality into this Terminal.

**Comment by daniyalw** [comment]
Hello @arnav56745, I added the 'cd' command. Also, thanks for reminding me about this project. It's been a long time since I last worked on it.

**Comment by arnav56745** [comment]
@daniyalw Thank you
